import { StyleSheet, Platform } from 'react-native';
import { C } from './theme';

export default StyleSheet.create({
  scrollContent: { paddingBottom: 60 },
  header: { paddingTop: Platform.OS === 'ios' ? 60 : 44, paddingHorizontal: 24, paddingBottom: 22, borderBottomWidth: 1, borderBottomColor: C.border },
  headerTag: { fontFamily: 'IBMPlexSans_500Medium', fontSize: 10, letterSpacing: 2.8, textTransform: 'uppercase', color: C.yellow, marginBottom: 6 },
  headerTitle: { fontFamily: 'BebasNeue_400Regular', fontSize: 52, letterSpacing: 2, lineHeight: 52, color: C.text },
  headerSub: { marginTop: 10, fontFamily: 'IBMPlexSans_300Light', fontSize: 12.5, color: C.textDim, lineHeight: 19 },
  section: { paddingHorizontal: 24, paddingTop: 22 },
  sectionLabel: { fontFamily: 'IBMPlexSans_500Medium', fontSize: 9.6, letterSpacing: 2.5, textTransform: 'uppercase', color: C.yellow, marginBottom: 10 },
  segControl: { flexDirection: 'row', backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 4, gap: 3 },
  segBtn: { flex: 1, paddingVertical: 10, paddingHorizontal: 8, borderRadius: 7, alignItems: 'center', justifyContent: 'center' },
  segBtnActive: { backgroundColor: C.yellow },
  segBtnText: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 12.5, color: C.textMid, textAlign: 'center', lineHeight: 17 },
  segBtnTextActive: { fontFamily: 'IBMPlexSans_500Medium', color: '#000' },
  grid3: { flexDirection: 'row', gap: 8 },
  grid2: { flexDirection: 'row', gap: 8 },
  inputBlock: { flex: 1, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 10, padding: 12, gap: 4 },
  inputBlockFocused: { borderColor: C.yellow },
  inputLabel: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 9.6, letterSpacing: 1.6, textTransform: 'uppercase', color: C.textDim },
  inputField: { fontFamily: 'IBMPlexMono_500Medium', fontSize: 20, color: C.text, padding: 0, margin: 0 },
  inputUnit: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 10, color: C.textDim },
  toggleRow: { flexDirection: 'row', gap: 8 },
  toggleChip: { flex: 1, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 8, padding: 11, flexDirection: 'row', alignItems: 'center', gap: 9 },
  toggleChipActive: { borderColor: C.yellow, backgroundColor: 'rgba(245,200,66,0.06)' },
  chipCheck: { width: 17, height: 17, borderRadius: 4, borderWidth: 1.5, borderColor: C.border, alignItems: 'center', justifyContent: 'center' },
  chipCheckActive: { backgroundColor: C.yellow, borderColor: C.yellow },
  chipCheckMark: { fontSize: 9, color: '#000', fontWeight: '700' },
  chipLabel: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 12.5, color: C.textMid, lineHeight: 19 },
  chipLabelActive: { color: C.text },
  chipSub: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 10, color: C.textDim },
  wallCard: { backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 12, marginBottom: 10, overflow: 'hidden' },
  wallCardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 14, paddingTop: 10 },
  wallName: { fontFamily: 'IBMPlexSans_500Medium', fontSize: 10, letterSpacing: 1.9, textTransform: 'uppercase', color: C.yellow },
  wallDel: { color: C.textDim, fontSize: 14, padding: 4 },
  wallFields: { flexDirection: 'row', alignItems: 'flex-end', paddingHorizontal: 14, paddingVertical: 8, gap: 8 },
  wallField: { flex: 1, gap: 3 },
  wallFieldLabel: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 8.8, letterSpacing: 1.6, textTransform: 'uppercase', color: C.textDim },
  wallFieldInput: { fontFamily: 'IBMPlexMono_500Medium', fontSize: 17.6, color: C.text, borderBottomWidth: 1, borderBottomColor: C.border, paddingBottom: 3, padding: 0, margin: 0 },
  wallSqftBadge: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 11.5, color: C.textMid, paddingBottom: 4, minWidth: 72, textAlign: 'right' },
  wallOpenings: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, paddingHorizontal: 14, paddingBottom: 12 },
  openingPill: { backgroundColor: 'transparent', borderWidth: 1, borderColor: C.border, borderRadius: 20, paddingVertical: 4, paddingHorizontal: 11 },
  openingPillOn: { backgroundColor: 'rgba(245,200,66,0.08)', borderColor: C.yellow },
  openingPillText: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 10.9, color: C.textDim },
  openingPillTextOn: { color: C.yellow },
  addWallBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderStyle: 'dashed', borderColor: C.border, borderRadius: 10, paddingVertical: 13, marginTop: 8 },
  addWallBtnText: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 12.8, color: C.textMid },
  resultCard: { marginHorizontal: 24, marginTop: 22, backgroundColor: C.yellow, borderRadius: 16, padding: 22 },
  resultTag: { fontFamily: 'IBMPlexSans_500Medium', fontSize: 9.6, letterSpacing: 2.5, textTransform: 'uppercase', color: 'rgba(0,0,0,0.45)', marginBottom: 4 },
  resultMain: { fontFamily: 'BebasNeue_400Regular', fontSize: 67, color: '#000', letterSpacing: 1, lineHeight: 67 },
  resultUnit: { fontFamily: 'IBMPlexSans_300Light', fontSize: 16 },
  resultDivider: { height: 1, backgroundColor: 'rgba(0,0,0,0.12)', marginVertical: 14 },
  resultBreakdown: { flexDirection: 'row', gap: 24 },
  breakdownVal: { fontFamily: 'IBMPlexMono_500Medium', fontSize: 16.8, color: '#000' },
  breakdownLabel: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 9.6, letterSpacing: 1.3, textTransform: 'uppercase', color: 'rgba(0,0,0,0.45)', marginTop: 2 },
  wallSummary: { marginHorizontal: 24, marginTop: 10, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 12, padding: 14 },
  wallSummaryTitle: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 9.6, letterSpacing: 2.2, textTransform: 'uppercase', color: C.textDim, marginBottom: 10 },
  wallSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 4, borderBottomWidth: 1, borderBottomColor: C.border },
  wallSummaryLeft: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 12.5, color: C.textMid },
  wallSummaryRight: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 12.5, color: C.text },
  shoppingCard: { marginHorizontal: 24, marginTop: 10, backgroundColor: C.surface, borderWidth: 1, borderColor: C.border, borderRadius: 14, padding: 16 },
  shoppingTitle: { fontFamily: 'IBMPlexSans_500Medium', fontSize: 9.6, letterSpacing: 2.5, textTransform: 'uppercase', color: C.yellow, marginBottom: 12 },
  shopItem: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: C.border },
  shopName: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 13.6, color: C.text },
  shopSub: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 10.9, color: C.textDim, marginTop: 2 },
  shopQty: { fontFamily: 'BebasNeue_400Regular', fontSize: 24, color: C.yellow, letterSpacing: 1 },
  tipBar: { marginHorizontal: 24, marginTop: 10, backgroundColor: 'rgba(245,200,66,0.05)', borderWidth: 1, borderColor: 'rgba(245,200,66,0.12)', borderRadius: 10, padding: 11 },
  tipText: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 11.7, color: C.textMid, lineHeight: 18 },
  tipStrong: { fontFamily: 'IBMPlexSans_500Medium', color: C.yellow },
  noResult: { marginHorizontal: 24, marginTop: 22, backgroundColor: C.surface, borderWidth: 1, borderStyle: 'dashed', borderColor: C.border, borderRadius: 14, padding: 30, alignItems: 'center' },
  noResultIcon: { fontSize: 28.8, marginBottom: 8, opacity: 0.3 },
  noResultText: { fontFamily: 'IBMPlexSans_400Regular', fontSize: 12.5, color: C.textDim, lineHeight: 19, textAlign: 'center' },
  openingDimRow: { flexDirection: 'row', gap: 8, marginTop: 8, maxWidth: 280 },
  wallOpeningDims: { paddingHorizontal: 14, paddingBottom: 10, gap: 8 },
  wallOpeningDimGroup: { gap: 4 },
  wallOpeningDimInputs: { flexDirection: 'row', alignItems: 'flex-end', gap: 5 },
  wallOpeningDimInput: { width: 38, textAlign: 'center' },
  wallOpeningDimSep: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 14, color: C.textDim, paddingBottom: 3 },
  wallOpeningDimUnit: { fontFamily: 'IBMPlexMono_400Regular', fontSize: 10, color: C.textDim, paddingBottom: 4 },
});
